cenas/accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.logear, name="accounts-login"),
    path('authenticate/', views.autenticar, name="accounts-authenticate"),
    path('logout/', views.cerrarsesion, name="accounts-logout"),
    path('panel/', views.panel, name="accounts-panel")
]

cenas/urls.py
from django.urls import path, include
from django.urls.conf import re_path
    
from . import views

app_name = 'cenas'
urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^cenas/', views.redirectcenas, name='redirectcenas'),
    path('<int:evento_id>/', views.detail, name='detail'),
    path('<int:pk>/recuento/', views.ResultsView.as_view(), name='recuento'),
    path('<int:evento_id>/seleccionar/', views.seleccionar, name='seleccionar'),
    path('eventos-selecciones/', views.seleccion_evento_obtener, name='eventos-selecciones'),
    path('obtener-selecciones/<int:evento_id>/', views.obtener_selecciones, name='obtener-selecciones')
]

# Importaciones de URL

urlpatterns += [
    re_path(r'^accounts/', include('cenas.accounts.urls'), name='accounts')
]

cenas/models.py
from django.db import models
from django.db.models.deletion import CASCADE, SET_NULL

class Evento(models.Model):
  tituloEvento = models.CharField("Evento", max_length=255, default="Evento")
  fechaEvento = models.DateField("Fecha del evento")
  activo = models.BooleanField("Activo", default=True)
  apuntados = models.JSONField(null=True, blank=True)
  siguienteEvento = models.ForeignKey('self', on_delete=SET_NULL, null=True, blank=True, verbose_name="Siguiente evento")
  permitirAlergenos = models.BooleanField(default=False, verbose_name="Permitir alérgenos")
  alergenos = models.JSONField(null=True, blank=True, verbose_name="Lista de alérgenos")

  def __str__(self):
    return self.tituloEvento

class Usuario(models.Model):
  dni = models.CharField(max_length=15, verbose_name="DNI", primary_key=True)
  nombre = models.CharField(max_length=255, verbose_name="Nombre")
  apellidos = models.CharField(max_length=255, verbose_name="Apellidos")

  def __str__(self):
    return self.nombre

class Seleccion(models.Model):
  idEvento = models.ForeignKey(Evento, on_delete=CASCADE)
  cena = models.CharField(max_length=100, verbose_name="Evento")
  recuento = models.IntegerField(default=0)
  usuarios = models.JSONField(null=True, blank=True)

  def __str__(self):
    return self.cena

cenas/accounts/views.py
# Django
from django.http import HttpResponseRedirect
from django.http.response import HttpResponse, HttpResponseBadRequest, HttpResponseBase, HttpResponseForbidden, HttpResponseGone, HttpResponseNotAllowed, HttpResponseRedirectBase
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views import generic
from django.contrib.auth import *
from django.contrib.auth.decorators import *

def logear(request):

    response = render(request, 'accounts/login.html')

    return response

def autenticar(request):

    if not request.POST:
        return HttpResponseNotAllowed(['POST'])

    if request.COOKIES.get('sessionid'):
        return HttpResponseRedirect(reverse('cenas:accounts-panel'))

    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)

    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse('cenas:accounts-panel'))
    else:
        error = "Usuario y/o contraseña incorrectos"
        context = { "error": error }
        return HttpResponseForbidden(render(request, 'accounts/login.html', context))

@login_required()
def panel(request):
    return HttpResponse(render(request, 'accounts/panel.html'))

@login_required()
def cerrarsesion(request):
    logout(request)
    return HttpResponseRedirect(reverse("cenas:index"))

cenas/views.py
# Django
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views import generic
from django.contrib.auth import *
from django.contrib.auth.decorators import *

# Modelos
from .models import Evento, Seleccion, Usuario

def index(request):
    listaEventos = Evento.objects.order_by('-fechaEvento').filter(activo = False)
    eventosActivos = Evento.objects.order_by('-fechaEvento').filter(activo = True)
    context = {'listaEventos': listaEventos, 'eventosActivos': eventosActivos}
    return render(request, 'cenas/index.html', context)

def redirectcenas():
    return redirect(to=reverse('cenas:index'), permanent=True)

def detail(request, evento_id):
    evento = get_object_or_404(Evento, pk=evento_id)
    dni = request.COOKIES.get('dni', "")
    context = {'evento': evento, 'dnialmacenado': dni}
    return render(request, 'cenas/detail.html', context)

class ResultsView(generic.DetailView):
    model = Evento
    template_name = 'cenas/recuento.html'

def seleccionar(request, evento_id):
    evento = get_object_or_404(Evento, pk=evento_id)
    try:
        cena_seleccionada = evento.seleccion_set.get(pk=request.POST['cena'])
    except (KeyError, Seleccion.DoesNotExist):
        return render(request, 'cenas/detail.html', {
            'evento': evento,
            'error_message': "No has seleccionado una cena.",
        })
    else:
        if not Usuario.objects.filter(dni=request.POST['dni']).exists():
            return render(request, 'cenas/detail.html', {
                'evento': evento,
                'error_message': "No existe el usuario indicado"
            })

        # Revisa las personas que ya están apuntadas y añadelas a la lisa de apuntados.
        if not Evento.objects.values_list('apuntados', flat=True).get(pk=evento.id):
            usuariosApuntados = []
        else:
            usuariosApuntados = list(Evento.objects.values_list('apuntados', flat=True).get(pk=evento.id))
        
        usuariosApuntadosFlat = []
        apuntado = False
        
        # Comprueba que el usuario esta presente, no guardaremos la nueva lista si existe
        for item in usuariosApuntados:
            if not item == "":
                usuariosApuntadosFlat.append(item)

        for apuntadoActual in usuariosApuntadosFlat:
            if not apuntadoActual:
                break
            if apuntadoActual == request.POST['dni']:
                apuntado = True
                break
            else:
                continue
        
        if apuntado == False:
            usuariosApuntadosFlat.append(request.POST['dni'])

      # Revisa la lista de alégenos si el usuario ha marcado que es alergeno.

        alergeno = request.POST.get('alergeno', False)

        usuariosAlergenosFlat =  []
        
        if alergeno == "True":
            if not Evento.objects.values_list('alergenos', flat=True).get(pk=evento.id):
                usuariosAlergenos = []
            else:
                usuariosAlergenos = list(Evento.objects.values_list('alergenos', flat=True).get(pk=evento.id))
            for item in usuariosAlergenos:
                if not item == "":
                    usuariosAlergenosFlat.append(item)
            if not usuariosAlergenosFlat:
                usuariosAlergenosFlat.append(request.POST['dni'])
        
        if evento.siguienteEvento:
            response = HttpResponseRedirect(reverse('cenas:detail', args=[Evento.objects.values_list('siguienteEvento', flat=True).get(pk=evento.id)]))
        else:
            response = HttpResponseRedirect(reverse('cenas:recuento', args=(evento.id, )))
        
        response.set_cookie('dni', request.POST['dni'], max_age=None, secure=True, httponly=True, samesite='Strict')
        evento.apuntados = usuariosApuntadosFlat
        evento.alergenos = usuariosAlergenosFlat
        evento.save(update_fields=['apuntados', 'alergenos'])

        # Revisa las personas que ya han seleccionado la opcion.
        if not Seleccion.objects.values_list('usuarios', flat=True).get(pk=request.POST['cena']):
            usuariosSeleccion = []
        else:
            usuariosSeleccion = list(Seleccion.objects.values_list('usuarios', flat=True).get(pk=request.POST['cena']))
        
        usuariosSeleccionFlat = []
        seleccionado = False
        
        # Comprueba que el usuario esta presente, no guardaremos la nueva lista si existe
        for item in usuariosSeleccion:
            if not item == "":
                usuariosSeleccionFlat.append(item)

        for usuarioActual in usuariosSeleccionFlat:
            if not usuarioActual:
                break
            if usuarioActual == request.POST['dni']:
                seleccionado = True
                break
            else:
                continue
        
        if seleccionado == False:
            usuariosSeleccionFlat.append(request.POST['dni'])

        cena_seleccionada.recuento += 1
        cena_seleccionada.usuarios = usuariosSeleccionFlat
        cena_seleccionada.save()
        return response

@login_required
def seleccion_evento_obtener(request):
    listaEventos = Evento.objects.order_by('-fechaEvento')
    context = {'listaEventos': listaEventos}
    return render(request, 'accounts/seleccionevento.html', context)

@login_required
def obtener_selecciones(request, evento_id):
    import django_excel as excel

    data = []

    cenas = Seleccion.objects.values_list('cena', flat=True).filter(idEvento=evento_id)
    cenasFlat = []

    for currentCena in cenas:
        if not currentCena == "":
            cenasFlat.append(currentCena)

    for currentCena in cenasFlat:
        usuarios = Seleccion.objects.filter(cena__exact=currentCena).values_list('usuarios', flat=True)
        usuariosFlat = []
        for item in usuarios:
            if item and not item == "":
                for currentUsuario in item:
                    dataUsuario = Usuario.objects.filter(dni__exact=currentUsuario).get()
                    if not dataUsuario:
                        continue
                    nombreCompletoUsuario = dataUsuario.nombre + ' ' + dataUsuario.apellidos
                    usuariosFlat.append(nombreCompletoUsuario)
        data += [[currentCena], usuariosFlat]

    return excel.make_response_from_array(data, 'xlsx', file_name='ListadoSelecciones-' + str(evento_id))

cenas/templates/cenas/detail.html
{% load i18n %}
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ evento.tituloEvento }} - {% translate "Eventos de Joe Doe" %}</title>
    <link rel="shortcut icon" href="{% static '/favicon.ico' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <a href="{% url 'cenas:index' %}"><img src="{% static '/cenas/logo.png' %}" alt="" width="30" height="24"></a>
        <span class="navbar-brand mb-0 h1">{% translate "Eventos de Joe Doe" %}</span>
      </div>
    </nav>
  </head>
  {% if not evento.activo %}
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <p class="text-error">{% translate "El evento actual no está activo" %}</p>
        </div>
      </div>
    </div>
  </body>
  {% else %}
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <h1>{{ evento.tituloEvento }}</h1>
          {% if error_message %}
            <p class="text-error"><strong>{{ error_message }}</strong></p>
          {% endif %}
          <form action="{% url 'cenas:seleccionar' evento.id %}" method="post">
            {% csrf_token %}
            {% for cena in evento.seleccion_set.all %}
              <input type="radio" class="form-check-input" name="cena" id="cena{{ forloop.counter }}" value="{{ cena.id }}"/>
              <label for="cena{{ forloop.counter }}" class="form-check-label">{{ cena.cena }}</label><br>
            {% endfor %}
            {% if evento.permitirAlergenos %}
              <input type="checkbox" class="form-check-input" name="alergeno" id="alergeno" value="True"/>
                <label for="alergeno" class="form-check-label">{% translate "¿Tienes alguna alergia?" %}</label>
            {% endif %}
              <div class="form-floating mb-3 mt-3">
                  <input class="form-control" type="text" name="dni" id="dni" value="{{ dnialmacenado }}" placeholder="" />
              <label for="dni">{% translate "Introduce tu identificación" %}</label>
            </div>
            <div class="mb-3">
              <input type="checkbox" class="form-check-input" name="recordar" id="recordar" value="True" />
              <label for="recordar">{% translate "¿Recordar identificación? (Almacenaremos una cookie, por lo que das tu consentimiento a que la almacenemos)" %}</label>
            </div>
            <input class="mb-5 btn btn-success" type="submit" value="Enviar">
          </form>
          <a href="{% url 'cenas:index' %}"><button class="btn btn-secondary" type="button">{% translate "Volver a la lista" %}</button></a>
        </div>
      </div>
    </div>
  </body>
  {% endif %}
</html>

cenas/templates/cenas/index.html
{% load i18n %}
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>{% translate "Eventos de Joe Doe" %}</title>
    <link rel="shortcut icon" href="{% static '/favicon.ico' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <a href="{% url 'cenas:index' %}"><img src="{% static '/cenas/logo.png' %}" alt="" width="30" height="24"></a>
        <span class="navbar-brand mb-0 h1">{% translate "Eventos de Joe Doe" %}</span>
      </div>
    </nav>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <h2 class="mt-3">{% translate "Eventos activos" %}</h2>
          {% if eventosActivos %}
          <table class="table">
              <tbody>
              {% for evento in eventosActivos %}
                  <tr>
                    <td>
                      <a href="{% url 'cenas:detail' evento.id %}">{{ evento.tituloEvento }} - {{ evento.fechaEvento }}</a>
                    </td>
                  </tr>
              {% endfor %}
            </tbody>
            </table>
          {% else %}
            <p>{% translate "No hay eventos activos" %}</p>
          {% endif %}
        </div>
      </div>
    </div>
  </body>
</html>

cenas/templates/cenas/recuento.html
{% load i18n %}
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>{% translate "Recuento - Eventos de Joe Doe" %}</title>
    <link rel="shortcut icon" href="{% static '/favicon.ico' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <a href="{% url 'cenas:index' %}"><img src="{% static '/cenas/logo.png' %}" alt="" width="30" height="24"></a>
        <span class="navbar-brand mb-0 h1">{% translate "Eventos de Joe Doe" %}</span>
      </div>
    </nav>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <table class="table">
            <tbody>
              {% for seleccion in evento.seleccion_set.all %}
              <tr>
                <td>
                  {{ seleccion.cena }}
                </td>
                <td>
                  {{ seleccion.recuento }}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <a href="{% url 'cenas:index' %}"><button class="btn btn-secondary" type="button">{% translate "Volver a la lista" %}</button></a>
        </div>
      </div>
    </div>
  </body>
</html>